### ISSUE TITLE
Issue restarting the odoo POD

### ISSUE THREAD

**Issue by jeremi** [OpenG2P/openg2p-erp-docker#11]
I followed the installation steps described in my PR #10 .
Odoo seemed stuck so I killed the odoo pod and it restarted, but now it seems stuck in an infinite loop restarting every few minutes and never going further than the `updating modules`.
![image](https://user-images.githubusercontent.com/9537/156890572-123c39aa-f97d-48b6-b287-b9cd8c698db5.png)

**Comment by jeremi** [comment]
I re-tried to setup few times, but the pod never restart properly.

The issue is:
```bash
Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-12.0.post20210915-py3.8.egg/odoo/addons/base/models/ir_module.py", line 337, in check_external_dependencies
    cls._check_external_dependencies(terp)
  File "/opt/bitnami/odoo/lib/odoo-12.0.post20210915-py3.8.egg/odoo/addons/base/models/ir_module.py", line 325, in _check_external_dependencies
    raise ImportError('No module named %s' % (pydep,))
ImportError: No module named cachetools
```

I imagine the reason is that the dependencies installed during the post-init phase (`customPostInitScripts`) are not present anymore in the pod when it is deleted and recreated by the `Deployments` manager.

**Comment by truthfool** [comment]
yes, post init scripts runs only once so you have to delete and install again.

**Comment by jeremi** [comment]
ok, what is the recommended way to run it for doing demos? And running in production?

**Comment by truthfool** [comment]
The flow starts from: Filling forms in ODK->ODK Connector pull those data->Registration->Beneficiary

**Comment by jeremi** [comment]
@truthfool What about hosting the app? (for demo and prod)
I tried the helm version but after a few minutes the POD is not working anymore (seems some concurrency problem) and then I cannot restart it. So it is not very usable.
