### ISSUE TITLE
issue setting up the dev environment

### ISSUE THREAD

**Issue by jeremi** [OpenG2P/openg2p-erp-docker#8]
I'm trying to setup the dev environment to test and demo OPENG2P.
I'm on linux and following the doc: https://github.com/OpenG2P/openg2p-erp-docker#developing-with-openg2p-crm-docker

I am getting the following error when I try to initialize the DB:
```shell
$ docker-compose run --rm odoo odoo --stop-after-init -i openg2p
...
2022-03-02 14:04:10,626 1 INFO devel odoo.modules.loading: loading base/views/res_config_settings_views.xml 
2022-03-02 14:04:10,644 1 INFO devel odoo.modules.loading: loading base/views/report_paperformat_views.xml 
2022-03-02 14:04:10,696 1 INFO devel odoo.modules.loading: loading base/views/onboarding_views.xml 
2022-03-02 14:04:10,751 1 INFO devel odoo.modules.loading: loading base/security/ir.model.access.csv 
2022-03-02 14:04:11,017 1 INFO devel odoo.modules.loading: Module base: loading demo 
2022-03-02 14:04:11,018 1 INFO devel odoo.modules.loading: loading base/data/res_company_demo.xml 
2022-03-02 14:04:11,030 1 INFO devel odoo.modules.loading: loading base/data/res_users_demo.xml 
2022-03-02 14:04:11,466 1 INFO devel odoo.modules.loading: loading base/data/res_partner_bank_demo.xml 
2022-03-02 14:04:11,474 1 INFO devel odoo.modules.loading: loading base/data/res_currency_rate_demo.xml 
2022-03-02 14:04:11,728 1 INFO devel odoo.modules.loading: loading base/data/res_bank_demo.xml 
2022-03-02 14:04:11,735 1 INFO devel odoo.modules.loading: loading base/data/res_partner_demo.xml 
2022-03-02 14:04:12,490 1 INFO devel odoo.modules.loading: loading base/data/res_partner_image_demo.xml 
2022-03-02 14:04:13,135 1 INFO devel odoo.modules.loading: 1 modules loaded in 16.03s, 0 queries 
2022-03-02 14:04:13,170 1 INFO devel odoo.modules.loading: updating modules list 
2022-03-02 14:04:13,170 1 INFO devel odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2022-03-02 14:04:13,650 1 INFO devel odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['openg2p'] to user __system__ #1 via n/a 
2022-03-02 14:04:14,041 1 WARNING devel odoo.modules.loading: Transient module states were reset 
2022-03-02 14:04:14,050 1 ERROR devel odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 324, in _check_external_dependencies
    importlib.import_module(pydep)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'apispec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 338, in check_external_dependencies
    cls._check_external_dependencies(terp)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 326, in _check_external_dependencies
    raise ImportError('No module named %s' % (pydep,))
ImportError: No module named apispec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 386, in load_modules
    modules.button_install()
  File "<decorator-gen-61>", line 2, in button_install
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 396, in button_install
    modules._state_update('to install', ['uninstalled'])
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 368, in _state_update
    update_demo = update_mods._state_update(newstate, states_to_update, level=level-1)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 374, in _state_update
    self.check_external_dependencies(module.name, newstate)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 346, in check_external_dependencies
    raise UserError(msg % (module_name, e.args[0]))
odoo.exceptions.UserError: ('Unable to install module "base_rest" because an external dependency is not met: No module named apispec', '')
2022-03-02 14:04:14,051 1 CRITICAL devel odoo.service.server: Failed to initialize database `devel`. 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 324, in _check_external_dependencies
    importlib.import_module(pydep)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'apispec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 338, in check_external_dependencies
    cls._check_external_dependencies(terp)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 326, in _check_external_dependencies
    raise ImportError('No module named %s' % (pydep,))
ImportError: No module named apispec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1164, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 386, in load_modules
    modules.button_install()
  File "<decorator-gen-61>", line 2, in button_install
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 396, in button_install
    modules._state_update('to install', ['uninstalled'])
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 368, in _state_update
    update_demo = update_mods._state_update(newstate, states_to_update, level=level-1)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 374, in _state_update
    self.check_external_dependencies(module.name, newstate)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 346, in check_external_dependencies
    raise UserError(msg % (module_name, e.args[0]))
odoo.exceptions.UserError: ('Unable to install module "base_rest" because an external dependency is not met: No module named apispec', '')
```

Did I miss something?

**Comment by truthfool** [comment]
Try these steps to deploy into k8s cluster : [https://github.com/OpenG2P/openg2p-erp-docker/tree/master/helm](https://github.com/OpenG2P/openg2p-erp-docker/tree/master/helm)

**Comment by jeremi** [comment]
Thank you, it worked with some slight adjustments. I create a PR to update the doc:
https://github.com/OpenG2P/openg2p-erp-docker/pull/10

Is there is a way to load some sample data to test it?

**Comment by truthfool** [comment]
Currently, we have removed sample data loading but you can pull from odk by making a few submissions. There is also a set of APIs for odk which I can provide for making quick submissions on odk side.
